cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00234.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00236.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00237.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00238.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00240.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00242.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00243.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00244.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00245.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00249.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00250.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00251.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00252.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00253.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00254.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00255.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00256.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00259.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00262.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00264.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00269.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00274.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00275.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00276.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00277.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00283.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00285.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00291.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00294.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00297.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00298.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00302.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00303.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00306.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00310.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00317.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00320.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00321.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00322.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00323.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00324.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00327.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00334.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00337.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00339.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00340.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00342.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00345.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00349.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00352.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00353.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00354.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00356.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00362.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00363.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00366.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00367.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00370.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00376.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00378.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00382.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00383.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00384.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00390.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00394.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00405.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00406.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00409.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00410.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00411.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00413.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00414.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00416.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00419.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00420.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00426.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00434.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00435.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00436.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00438.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00656.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00657.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00660.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00661.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00664.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00665.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00667.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00668.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00670.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00675.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00676.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00678.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00687.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00688.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00690.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00691.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00694.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00695.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00696.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00697.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00699.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00701.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00702.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00704.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00705.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00706.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00707.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00708.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00709.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00713.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00714.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00719.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00721.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00724.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00726.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00733.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00737.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00739.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00742.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00743.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00745.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00749.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00751.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00753.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00755.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00758.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00759.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00761.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00762.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00765.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00766.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00767.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00771.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00773.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00776.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00777.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00779.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00783.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00787.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00788.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00791.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00793.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00794.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00795.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00797.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00798.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00801.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00802.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00808.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00811.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00812.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00814.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00816.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00820.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00821.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00825.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00827.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00828.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00830.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00831.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00833.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00835.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00836.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00838.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00840.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00842.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00844.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00846.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00847.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00849.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00851.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00853.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00854.npy ./
cp /mnt/nas_kradar/kradar_dataset/dir_all/9/radar_zyx_cube_npy_f32/cube_00855.npy ./