from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from yacs.config import CfgNode as CN

# configs for HRNet3D
HRNET3D = CN()
HRNET3D.FINAL_CONV_KERNEL = 1
HRNET3D.WITH_HEAD = False

HRNET3D.STAGE2 = CN()
HRNET3D.STAGE2.NUM_MODULES = 1
HRNET3D.STAGE2.NUM_BRANCHES = 2
HRNET3D.STAGE2.NUM_BLOCKS = [4, 4]
HRNET3D.STAGE2.NUM_CHANNELS = [2, 4]
HRNET3D.STAGE2.BLOCK = "BASIC"
HRNET3D.STAGE2.FUSE_METHOD = "SUM"

HRNET3D.STAGE3 = CN()
HRNET3D.STAGE3.NUM_MODULES = 4
HRNET3D.STAGE3.NUM_BRANCHES = 3
HRNET3D.STAGE3.NUM_BLOCKS = [4, 4, 4]
HRNET3D.STAGE3.NUM_CHANNELS = [2, 4, 8]
HRNET3D.STAGE3.BLOCK = "BASIC"
HRNET3D.STAGE3.FUSE_METHOD = "SUM"

HRNET3D.STAGE4 = CN()
HRNET3D.STAGE4.NUM_MODULES = 3
HRNET3D.STAGE4.NUM_BRANCHES = 4
HRNET3D.STAGE4.NUM_BLOCKS = [4, 4, 4, 4]
HRNET3D.STAGE4.NUM_CHANNELS = [2, 4, 8, 16]
HRNET3D.STAGE4.BLOCK = "BASIC"
HRNET3D.STAGE4.FUSE_METHOD = "SUM"



HRNET3D_Tiny = CN()
HRNET3D_Tiny.INPLANES = 8
HRNET3D_Tiny.STAGE2 = CN()
HRNET3D_Tiny.STAGE2.NUM_MODULES = 1
HRNET3D_Tiny.STAGE2.NUM_BRANCHES = 2
HRNET3D_Tiny.STAGE2.NUM_BLOCKS = [2, 2]
HRNET3D_Tiny.STAGE2.NUM_CHANNELS = [8, 16]
HRNET3D_Tiny.STAGE2.BLOCK = "ResNetBlock"
HRNET3D_Tiny.STAGE2.FUSE_METHOD = "SUM"

HRNET3D_Tiny.STAGE3 = CN()
HRNET3D_Tiny.STAGE3.NUM_MODULES = 1
HRNET3D_Tiny.STAGE3.NUM_BRANCHES = 3
HRNET3D_Tiny.STAGE3.NUM_BLOCKS = [2, 2, 2]
HRNET3D_Tiny.STAGE3.NUM_CHANNELS = [8, 16, 32]
HRNET3D_Tiny.STAGE3.BLOCK = "ResNetBlock"
HRNET3D_Tiny.STAGE3.FUSE_METHOD = "SUM"


HRNET3D_Tiny_feat16 = CN()
HRNET3D_Tiny_feat16.INPLANES = 16
HRNET3D_Tiny_feat16.STAGE2 = CN()
HRNET3D_Tiny_feat16.STAGE2.NUM_MODULES = 1
HRNET3D_Tiny_feat16.STAGE2.NUM_BRANCHES = 2
HRNET3D_Tiny_feat16.STAGE2.NUM_BLOCKS = [2, 2]
HRNET3D_Tiny_feat16.STAGE2.NUM_CHANNELS = [16, 32]
HRNET3D_Tiny_feat16.STAGE2.BLOCK = "ResNetBlock"
HRNET3D_Tiny_feat16.STAGE2.FUSE_METHOD = "SUM"

HRNET3D_Tiny_feat16.STAGE3 = CN()
HRNET3D_Tiny_feat16.STAGE3.NUM_MODULES = 1
HRNET3D_Tiny_feat16.STAGE3.NUM_BRANCHES = 3
HRNET3D_Tiny_feat16.STAGE3.NUM_BLOCKS = [2, 2, 2]
HRNET3D_Tiny_feat16.STAGE3.NUM_CHANNELS = [16, 32, 64]
HRNET3D_Tiny_feat16.STAGE3.BLOCK = "ResNetBlock"
HRNET3D_Tiny_feat16.STAGE3.FUSE_METHOD = "SUM"

# The following results wil be used for the final submission

HRNET3D_Tiny_feat16_small = CN()
HRNET3D_Tiny_feat16_small.LAYER1 = CN()
HRNET3D_Tiny_feat16_small.LAYER1.INPLANES = 1
HRNET3D_Tiny_feat16_small.LAYER1.BLOCK = "ResNetBlock"

HRNET3D_Tiny_feat16_small.STAGE2 = CN()
HRNET3D_Tiny_feat16_small.STAGE2.INPLANES = 16
HRNET3D_Tiny_feat16_small.STAGE2.NUM_MODULES = 1
HRNET3D_Tiny_feat16_small.STAGE2.NUM_BRANCHES = 2
HRNET3D_Tiny_feat16_small.STAGE2.NUM_BLOCKS = [1, 1]
HRNET3D_Tiny_feat16_small.STAGE2.NUM_CHANNELS = [16, 32]
HRNET3D_Tiny_feat16_small.STAGE2.BLOCK = "ResNetBlock"
HRNET3D_Tiny_feat16_small.STAGE2.FUSE_METHOD = "SUM"

HRNET3D_Tiny_feat16_small.STAGE3 = CN()
HRNET3D_Tiny_feat16_small.STAGE3.NUM_MODULES = 1
HRNET3D_Tiny_feat16_small.STAGE3.NUM_BRANCHES = 3
HRNET3D_Tiny_feat16_small.STAGE3.NUM_BLOCKS = [1, 1, 1]
HRNET3D_Tiny_feat16_small.STAGE3.NUM_CHANNELS = [16, 32, 64]
HRNET3D_Tiny_feat16_small.STAGE3.BLOCK = "ResNetBlock"
HRNET3D_Tiny_feat16_small.STAGE3.FUSE_METHOD = "SUM"


MODEL_CONFIGS = {
    "hrnet3D": HRNET3D,
    "hr_tiny": HRNET3D_Tiny,
    "hr_tiny_feat16": HRNET3D_Tiny_feat16,
    "hr_tiny_feat16_small": HRNET3D_Tiny_feat16_small,
}
